# Site settings
title: YangYi's Blog
email: yangyi_bupt@126.com
description: > # this means to ignore newlines until "baseurl:"
  整理平时所得于此地,回头看希望有所积累
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yangyi-bupt.github.io" # the base hostname & protocol for your site
github_username:  yangyi-bupt

# Build settings
markdown: kramdown
